FROM debian:buster
RUN apt-get update && DEBIAN_FRONTEND=noninteractive apt-get install -y \
    curl \
    && rm -rf /var/lib/apt/lists/*
RUN curl -sL https://deb.nodesource.com/setup_14.x | bash -
RUN apt-get update && DEBIAN_FRONTEND=noninteractive apt-get install -y \
    nodejs \
    && rm -rf /var/lib/apt/lists/*
RUN nodejs --version
RUN npm --version
WORKDIR /build
COPY . .
COPY docker_entrypoint.sh /usr/local/bin/docker_entrypoint.sh
ENTRYPOINT [ "bash", "/usr/local/bin/docker_entrypoint.sh" ]
